"""Initial migration

Revision ID: 4f3b589d2a6e
Revises: 
Create Date: 2021-11-24 12:50:45.410472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f3b589d2a6e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('set_exercise_id_fkey', 'set', type_='foreignkey')
    op.create_foreign_key(None, 'set', 'exercise', ['exercise_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'set', type_='foreignkey')
    op.create_foreign_key('set_exercise_id_fkey', 'set', 'workout', ['exercise_id'], ['id'])
    # ### end Alembic commands ###
